### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by Jhinxs** [WWFWT/TinyVT#1]
不知道是怎么测的1903 双核 测试不行 ept无hook，而且赶紧ept建立的地方有问题，应该会产出ept violation exit，有点像vttome github上的一份代码

**Comment by WWFWT** [comment]
需要自己去改hook代码，这里获取ssdt的方法过时了，况且系统不同ssdt下标也不一样。目前推荐去读符号表的方法获取。
ept建立的地方的问题，不知道你说的是会出现什么问题。目前见过的是请求太大的内存，内存不够导致失败。内存分配合理的话，一般不会出啥问题，它就是用来存些表而已
